### PR TITLE
Initialize post with query params

### PR DESCRIPTION
**Pull request by eonwarped**
This is for eventually being able to link to file support tickets directly. There is likely a length limitation on the URL, however.

# Changes proposed in this pull request:
- Pull in title, category, content from query parameters
- Change to category additions to enable reactivity for the category change.

### CODE REVIEW

**Comment by eonwarped** [comment]
I'm observing both of these behaviors on test.tokenbb.io  hum.... but I'll take a look.

**Comment by eonwarped** [comment]
Oh I see... there is something funny going on. I think I identified it.

**Comment by eonwarped** [comment]
Alright! I got it working smoothly in both places now, in a consistent manner.

**Comment by reggaemuffin** [comment]
So my current test on the staging site shows that the query parameter works now.

https://support.tokenbb.bt-stage.com/new?category=general
works great but if you are on a home page with category selected and click new, said category is removed and you get to https://support.tokenbb.bt-stage.com/new

**Comment by eonwarped** [comment]
Ooh right. I will add that!

**Comment by eonwarped** [comment]
Done!

**Comment by reggaemuffin** [comment]
awesome! testing the change :)

**Pull request merged**
