### PR TITLE
Collapse groups by default

### PR DESCRIPTION
**Pull request by eonwarped**
For @thecryptodrive :)

Do you think this should only be done if the number of groups starts out large? I'll set that to collapse by default if the number of groups is 3 or more. One moment then...

### CODE REVIEW

**Comment by reggaemuffin** [comment]
Auto-collapsed should be a setting just like hide that can be done per group and auto-collapses that specific group

**Comment by thecryptodrive** [comment]
group or category yeah

**Comment by reggaemuffin** [comment]
> group or category yeah

categories cannot be collapsed. They can be hidden.

**Comment by thecryptodrive** [comment]
my bad sorry, yes to specify why group will be collapsed or not for granular control, ie might want just the first one expanded and the rest collapsed, or one in the middle expanded and the rest collapsed.

**Comment by eonwarped** [comment]
I'm confused. What's the desired behavior?

**Comment by reggaemuffin** [comment]
image

Something like this, a `collapsed` checkmark on each category group. If that checkmark is true, that group is collapsed by default. Otherwise it is open by default

**Comment by thecryptodrive** [comment]
exactly that

**Comment by eonwarped** [comment]
Ok, done.

**Pull request merged**
