### PR TITLE
Admin Category Settings Improvements

### PR DESCRIPTION
**Pull request by eonwarped**
* Adds drag icon when modifying order
* Adding ats/groups will append to the end and scroll to location by default
* Dropdown menu for context, and expandable edit pane for goups/cats.

### CODE REVIEW

**Comment by eonwarped** [comment]
image

**Comment by nojo121** [comment]
Nice work,
i think this prob. interferes with my pr #133.
How sould we go on?

**Comment by nojo121** [comment]
Nice work,
i think this prob. interferes with my pr #133.
How sould we go on?

**Comment by reggaemuffin** [comment]
Regarding #133 we should merge this first and then apply the smaller changes, maybe git will automatically do the right thing.

**Comment by nojo121** [comment]
There's a bug, if you hover over the first element and want to click on one of the appearing items, they disappear and the items from the second element appear.

**Comment by reggaemuffin** [comment]
image

can we move this to two icons, one folder, one plus? I think that is better UX :)

**Comment by reggaemuffin** [comment]
merged this together with #133 and we can make a new pr for the dropdown to icons (or have a discussion about it first)

**Pull request merged**
